name: Pharmaceutical-Sales-prediction
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: create features
        run: |
          pip install -r requirements.txt
          cd scripts/
          python create_features.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

            echo "## Model Training Completed" > report.md
