name: Pharmaceutical-Sales-prediction

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Train model
              env:
                  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  cml ci --unshallow
                  pip install -r requirements.txt  # Install dependencies
                  #dvc repro                        # Reproduce pipeline
            - name: Write CML report
              run: |
                  python scripts/file_handler.py
                   - name: Write CML report
