name: Pharmaceutical-Sales-prediction

on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2 
      - name: file handler
        run: |
          pip install -r requirements.txt
          cd scripts/
          python create_.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
